'use strict';
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.storeFactory = exports.CollectionStore = exports.DocumentStore = exports.CountStore = exports.AStore = exports.DataMiddlewareMap = exports.executeOnFilesRecursively = exports.executeProcessesInFolder = exports.executeWorker = exports.executeWatcher = exports.executeCronjob = exports.addActionWorkers = exports.addActionWatchers = exports.addActionCronjobs = exports.initiateWorkers = exports.initiateWatchers = exports.initiateCronjobs = exports.BackendRegistry = exports.EStoreType = exports.OwservableClient = void 0;
const owservable_client_1 = __importDefault(require("./owservable.client"));
exports.OwservableClient = owservable_client_1.default;
const store_type_enum_1 = __importDefault(require("./enums/store.type.enum"));
exports.EStoreType = store_type_enum_1.default;
const backend_registry_1 = __importDefault(require("./backend/backend.registry"));
exports.BackendRegistry = backend_registry_1.default;
const initiate_workers_1 = __importDefault(require("./functions/initiate.workers"));
exports.initiateWorkers = initiate_workers_1.default;
const initiate_cronjobs_1 = __importDefault(require("./functions/initiate.cronjobs"));
exports.initiateCronjobs = initiate_cronjobs_1.default;
const initiate_watchers_1 = __importDefault(require("./functions/initiate.watchers"));
exports.initiateWatchers = initiate_watchers_1.default;
const add_action_cronjobs_1 = __importDefault(require("./functions/action/add.action.cronjobs"));
exports.addActionCronjobs = add_action_cronjobs_1.default;
const add_action_watchers_1 = __importDefault(require("./functions/action/add.action.watchers"));
exports.addActionWatchers = add_action_watchers_1.default;
const add_action_workers_1 = __importDefault(require("./functions/action/add.action.workers"));
exports.addActionWorkers = add_action_workers_1.default;
const execute_cronjob_1 = __importDefault(require("./functions/execute/execute.cronjob"));
exports.executeCronjob = execute_cronjob_1.default;
const execute_watcher_1 = __importDefault(require("./functions/execute/execute.watcher"));
exports.executeWatcher = execute_watcher_1.default;
const execute_worker_1 = __importDefault(require("./functions/execute/execute.worker"));
exports.executeWorker = execute_worker_1.default;
const execute_processes_in_folder_1 = __importDefault(require("./functions/execute/execute.processes.in.folder"));
exports.executeProcessesInFolder = execute_processes_in_folder_1.default;
const execute_on_files_recursively_1 = __importDefault(require("./functions/execute/execute.on.files.recursively"));
exports.executeOnFilesRecursively = execute_on_files_recursively_1.default;
const data_middleware_map_1 = __importDefault(require("./middleware/data.middleware.map"));
exports.DataMiddlewareMap = data_middleware_map_1.default;
const a_store_1 = __importDefault(require("./store/a.store"));
exports.AStore = a_store_1.default;
const count_store_1 = __importDefault(require("./store/count.store"));
exports.CountStore = count_store_1.default;
const document_store_1 = __importDefault(require("./store/document.store"));
exports.DocumentStore = document_store_1.default;
const collection_store_1 = __importDefault(require("./store/collection.store"));
exports.CollectionStore = collection_store_1.default;
const store_factory_1 = __importDefault(require("./store/factories/store.factory"));
exports.storeFactory = store_factory_1.default;
const OwservableCore = {};
exports.default = OwservableCore;
//# sourceMappingURL=owservable.core.js.map