import { Subject, Subscription } from 'rxjs';
import EStoreType from '../enums/store.type.enum';
import IObservableBackend from '../backend/i.observable.backend';
import StoreSubscriptionConfigType from '../types/store.subscription.config.type';
import 'json-circular-stringify';
export default abstract class AStore extends Subject<any> {
    protected _backend: IObservableBackend;
    protected _target: string;
    protected _type: EStoreType;
    protected _config: StoreSubscriptionConfigType;
    protected _incremental: boolean;
    protected _subscriptionId: string;
    protected _query: any;
    protected _sort: any;
    protected _fields: any;
    protected _paging: any;
    protected _populates: any[];
    protected _virtuals: any[];
    protected _delay: number;
    protected _subscription: Subscription;
    protected _subscriptionDiffs: Map<string, boolean>;
    protected constructor(backend: IObservableBackend, target: string);
    destroy(): void;
    restartSubscription(): void;
    protected isInitialSubscription(change: any): boolean;
    protected abstract shouldReload(change: any): boolean;
    protected abstract load(change: any): Promise<void>;
    protected extractFromConfig(): void;
    protected testDocument(document: any): boolean;
    protected set subscription(subscription: Subscription);
    protected get backend(): IObservableBackend;
    protected emitOne(startTime: number, subscriptionId: string, update?: any): void;
    protected emitMany(startTime: number, subscriptionId: string, update?: any): void;
    protected emitTotal(startTime: number, subscriptionId: string, total: any): void;
    protected emitDelete(startTime: number, subscriptionId: string, deleted: any): void;
    protected emitError(startTime: number, subscriptionId: string, error: any): void;
    protected shouldConsiderFields(): boolean;
    set config(config: StoreSubscriptionConfigType);
    get target(): string;
    protected removeSubscriptionDiff(subId: string): void;
    protected isQueryChange(subId: string): boolean;
    private _isValidConfig;
    private _addSubscriptionDiff;
    private _responseStatistics;
}
